# Starting yaml travis ci integration file

language: node_js
node_js:
   - "6"
   - "8"
cache:
  directories:
    - ~/.npm
before_install:
  - npm i -g npm@5
script:
  - npm run build
  - npm test
sudo: false
